#!/usr/bin/perl

# perms: total rewrite of horrid DoC-specific 040perms and 042mkdirlexis,
# using a simple declarative little language (in the config tree) that
# tells us what to do.  So this is essentially a state machine interpreter
# for that little language.

=head1 NAME

maint perms

=head1 SYNOPSIS

maint [standard-maint-args] perms

=head1 DESCRIPTION

This reads a configuration file, written in a simple declarative little
language that describes permissions/facls/ownership/group-ownership for
a series of files and directories, and enforces them.

=head2 Options

Standard maint args, no others.

=cut

use strict;
use warnings;

use Maint qw(:all);
use Maint::Perms qw(:all);
use Data::Dumper;

maint_init();

maint_usage() unless @ARGV == 0;

my $confdir = maint_getconfigdir();
my $datafile = maint_getconfig( "perms:data" ) // 'perms/data';

$datafile = "$confdir/$datafile";
maint_fatalerror( "No datafile text $datafile!" ) unless -f $datafile;

maint_setperms( $datafile );

maint_exit();


=head1 AUTHORS

Duncan White E<lt>dcw@imperial.ac.ukE<gt>,

=head1 COPYRIGHT AND LICENSE

Copyright 2018 Department of Computing, Imperial College London

=cut
